# Generated by Django 3.0.7 on 2020-06-11 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='account', serialize=False, to=settings.AUTH_USER_MODEL, to_field='username')),
                ('picture', models.ImageField(default='/default/avatar/avatar.png', upload_to='avatars/%Y/%m/%d/')),
                ('moment', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['moment'],
                'get_latest_by': 'moment',
            },
        ),
    ]
