# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='picture',
            field=models.ImageField(default='/default/avatar/avatar.png', unique=True, upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
