# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 17:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20171218_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='/default/avatar/avatar.png', upload_to='avatars/%Y/%m/%d/')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.RemoveField(
            model_name='avatars',
            name='username',
        ),
        migrations.DeleteModel(
            name='Avatars',
        ),
    ]
