# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 18:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171231_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
