# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloging', '0004_auto_20171231_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataForArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloging.Articles', to_field='name')),
            ],
        ),
    ]
