# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataforarticles',
            name='article',
        ),
        migrations.RemoveField(
            model_name='dataforarticles',
            name='text',
        ),
    ]
