# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_auto_20180118_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataForArticles',
        ),
    ]
