# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
