# Generated by Django 3.0.7 on 2020-06-11 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('name', models.TextField(error_messages={'unique': 'NOT UNIQUE'}, primary_key=True, serialize=False)),
                ('picture', models.ImageField(default='/default/blogsMainImage/859_big.jpg', upload_to='blogsMainImage/%Y/%m/%d/')),
                ('about', models.TextField(null=True)),
                ('moment', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', related_query_name='blog', to='account.Profile')),
            ],
            options={
                'ordering': ['moment'],
                'get_latest_by': 'moment',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField(auto_now=True)),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', related_query_name='subscriber', to='bloging.Blogs')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', related_query_name='subscribe', to='account.Profile')),
            ],
            options={
                'ordering': ['moment'],
                'get_latest_by': 'moment',
            },
        ),
        migrations.AddField(
            model_name='blogs',
            name='subscribe',
            field=models.ManyToManyField(related_name='a', through='bloging.Subscribe', to='account.Profile'),
        ),
    ]
