# Generated by Django 2.2 on 2019-04-29 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('picture', models.ImageField(default='/default/blogsMainImage/859_big.jpg', upload_to='blogsMainImage/%Y/%m/%d/')),
                ('about', models.TextField(null=True)),
                ('subscribers', models.BigIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile', to_field='username')),
            ],
        ),
    ]
