<<<<<<< HEAD
# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20171231_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('picture', models.ImageField(default='/default/blogsMainImage/859_big.jpg', upload_to='blogsMainImage/%Y/%m/%d/')),
                ('about', models.TextField()),
                ('subscribers', models.BigIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile', to_field='username')),
            ],
        ),
    ]
=======
# Generated by Django 2.2 on 2019-07-03 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('name', models.TextField(error_messages={'unique': 'NOT UNIQUE'}, primary_key=True, serialize=False)),
                ('picture', models.ImageField(default='/default/blogsMainImage/859_big.jpg', upload_to='blogsMainImage/%Y/%m/%d/')),
                ('about', models.TextField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', related_query_name='blog', to='account.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', related_query_name='subscriber', to='bloging.Blogs')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', related_query_name='subscribe', to='account.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='blogs',
            name='subscribe',
            field=models.ManyToManyField(related_name='a', through='bloging.Subscribe', to='account.Profile'),
        ),
    ]
>>>>>>> dev
