# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
