# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloging', '0006_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
